name: Copy files to jekyll repo

on:
  workflow_dispatch:
  schedule:
    - cron: '14 3 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  copy_to_jekyll:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: wikipathways-database
          submodules: true
          fetch-depth: 0
          
      - name: Checkout jekyll repo
        uses: actions/checkout@v2
        with:
          repository: wikipathways/wikipathways.github.io
          path: wikipathways.github.io
          submodules: true
          fetch-depth: 0
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}   ## for push into cookbook-dev

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          cp wikipathways-database/pathways/*/*.md wikipathways.github.io/_pathways/
          cp wikipathways-database/pathways/*/*-bibliography.tsv wikipathways.github.io/_data/
          cp wikipathways-database/pathways/*/*-datanodes.tsv wikipathways.github.io/_data/
          cd wikipathways.github.io
          git add _pathways/*.md
          git add _data/*.tsv
          if git diff --exit-code --staged > /dev/null; then
              echo "No changes"
          else
              git commit -m 'Update tsv and md files'
              git push
          fi
